# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quanticle's Blog
email: quanticle@quanticle.net
description: > # this means to ignore newlines until "baseurl:"
  A blog where I discuss what I'm reading and why it's good (or bad).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quanticle.net" # the base hostname & protocol for your site
twitter_username: quanticle
github_username:  quanticle

# Build settings
markdown: kramdown
kramdown:
    input: GFM
theme: minima

# Dev Server settings
host: 0.0.0.0
port: 4000
